apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-root-ca
  namespace: cert-manager
spec:
  isCA: true
  duration: 87600h
  secretName: lab-root-ca
  commonName: lab-root-ca.lab.local
  dnsNames:
    - lab-root-ca.lab.local
  issuerRef:
    name: lab-selfsigned
    kind: ClusterIssuer