apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-lab-local
  namespace: cert-manager
spec:
  secretName: wildcard-lab-local
  duration: 8760h
  dnsNames:
    - '*.lab.local'
  issuerRef:
    name: lab-ca
    kind: ClusterIssuer